name: Peel Water Bill Checker
version: "1.0.31"
slug: peel_bill_checker
description: Checks Region of Peel water bills

arch:
  - amd64

startup: application
boot: auto

image: "ghcr.io/home-assistant/{arch}-base-python"

options:
  email: ""
  password: ""

schema:
  email: str
  password: password
