name: "Peel Water Bill Checker"
version: "1.0.26"
slug: "peel_bill_checker"
description: "Checks Region of Peel water bills"
arch:
  - amd64

startup: application
boot: auto

options:
  email: ""
  password: ""

schema:
  email: str
  password: password
